version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: server
    binary: go-anon-server
    dir: ./cmd/server
    targets: [go_first_class]
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: anon-doc
    binary: anon-doc
    dir: ./cmd/anon-doc
    targets: [go_first_class]
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: server
    builds: [server]
    name_template: "go-anon-server_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: anon-doc
    builds: [anon-doc]
    name_template: "anon-doc_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  name_template: "v{{ .Version }}"
